c4sh/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import auth
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('django.contrib.auth.views',
	url(r'^login/$', 'login', {'template_name': 'base/login.html'}, name="login"),
	#url(r'^logout/$', 'logout', {'next_page': '/'}, name="logout"),
)

urlpatterns += patterns('c4sh.desk.views',
	url(r'^logout/$', 'logout_view', name="logout"),
	url(r'^ask-logout/$', 'ask_logout_view', name="ask-logout"),
	url(r'^$', 'dashboard_view', name="dashboard"),
	url(r'^sell/$', 'sell_action', name="desk-sell"),
	url(r'^sell/(?P<sale_id>\d+)/$', 'sell_action', name="desk-sell-fulfill"),
	url(r'^sale/(?P<sale_id>\d+)/$', 'sale_view', name='desk-sale'),
	url(r'^reverse/(?P<sale_id>\d+)/$', 'reverse_sale_view', name='desk-sale-reverse'),
)

urlpatterns += patterns('c4sh.backend.views',
	url(r'^monitor/$', 'monitor_view', name="monitor"),
	url(r'^backend/$', 'dashboard_view', name="backend-dashboard"),
	url(r'^backend/cashdesks/$', 'cashdesks_view', name="backend-cashdesks"),
	url(r'^backend/cashdesks/cashier/add/$', 'cashdesks_cashier_add_view', name="backend-cashdesks-cashier-add"),

	url(r'^backend/cashdesks/session/add/$', 'cashdesks_session_add_view', name="backend-cashdesks-session-add"),
	url(r'^backend/cashdesks/session/edit/(?P<session_id>\d+)/$', 'cashdesks_session_edit_view', name="backend-cashdesks-session-edit"),
	url(r'^backend/cashdesks/session/report/(?P<session_id>\d+)/$', 'cashdesks_session_report_view', name="backend-cashdesks-session-report"),

	url(r'^backend/sales/$', 'sales_view', name="backend-sales"),

	url(r'^backend/sale/(?P<sale_id>\d+)/$', 'sale_detail_view', name="backend-sale-detail"),
	url(r'^backend/sale/reverse/(?P<sale_id>\d+)/$', 'sale_reverse_view', name='backend-sale-reverse'),

	url(r'^fail/', 'static_view', {'template': 'fail.html'}, name="fail"),
)

urlpatterns += patterns('',
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
   (r'^api/', include('c4sh.api.urls')),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        	{'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
	)
	urlpatterns += staticfiles_urlpatterns()

c4sh/backend/models.py
from django.db import models
from django.contrib.auth.models import User
#from c4sh.preorder.models import PreorderTicket

class UserProfile(models.Model):
	"""
	This is the UserProfile model.
	It can be constructed using (django.contrib.auth.models.)User.get_profile().
	"""
	user = models.ForeignKey(User)

	supervisor_auth_code = models.CharField(max_length=64, unique=True, verbose_name="Superuser authentication code for special tickets, UUID", null=True, blank=True)

	created_by = models.ForeignKey(User, null=True, blank=True, verbose_name="User has been created by..", related_name="user_created_by")

	def __unicode__(self):
		return "%s" % self.user.username

class Ticket(models.Model):
	"""
	This is the Ticket model. It defines the various available ticket types.
	Please be aware that there cannot be an edit or delete function for this model.
	Instead, the software should create a copy of the Ticket instance and set the old
	one to deleted=True. That way, SalePosition references won't get fucked up.
	"""
	name = models.CharField(max_length=255, verbose_name="Ticket name (internal)")
	receipt_name = models.CharField(max_length=255, verbose_name="Ticket name (to show on receipt)")
	invoice_name = models.CharField(max_length=255, verbose_name="Ticket name (to show on invoice)")
	description = models.TextField(blank=True, null=True, verbose_name="Optional verbose description of the ticket type (internal)")

	sale_price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ticket price (money to collect at cash desk)")
	invoice_price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Ticket price (to show on invoice and receipt -- including tax)")
	currency = models.CharField(max_length=3, default="EUR") # Enirely cosmetic right now, no conversations planned

	tax_rate = models.SmallIntegerField(default=19, verbose_name="Included tax rate in percent")
	rabate_rate = models.SmallIntegerField(default=0, verbose_name="Included instant rabate in percent")

	limit_timespan = models.BooleanField(default=False, verbose_name="Can this ticket only be sold within a certain timespan?")
	valid_from = models.DateTimeField(blank=True, null=True, verbose_name="Ticket can be sold from..")
	valid_until = models.DateTimeField(blank=True, null=True, verbose_name="Ticket can be sold until..")

	limit_supervisor = models.BooleanField(default=False, verbose_name="Does this ticket need supervisor authorization?")
	limit_honorary_member = models.BooleanField(default=False, verbose_name="Can this ticket only be bought by a honorary member? (e.g. Chaosnummer required)")

	preorder_sold = models.BooleanField(default=False, verbose_name="Is this a ticket sold through preorder? (If so, it will not be displayed in the ticket list and can only be added with QRCode/UUID)")

	receipt_autoprint = models.BooleanField(default=True, verbose_name="Print a receipt for this ticket automatically?")
	receipt_advice = models.TextField(blank=True, null=True, verbose_name="Additional text to be printed on receipt when buying this ticket")

	invoice_autoprint = models.BooleanField(default=True, verbose_name="Print an invoice for this ticket automatically?")
	invoice_advice = models.TextField(blank=True, null=True, verbose_name="Additional text to be printed on invoice when buying this ticket")

	#valid_payment_types = models.ManyToManyField("PaymentType", verbose_name="Valid payment types")

	active = models.BooleanField(default=False, verbose_name="Is active (will show up in cashier frontend)?")
	deleted = models.BooleanField(default=False, verbose_name="Is deleted (won't show up in supervisor backend)?")

	def __unicode__(self):
		return "%s (%.2f %s)" % (self.name, self.sale_price, self.currency)

	def delete(self):
		# No real deletion here. See above.
		self.deleted = True
		self.active = False
		return super(self, Ticket).save()

	"""def is_preorderable(self):
		try:
			return PreorderTicket.objects.get(backend_id=self.pk)
		except PreorderTicket.DoesNotExist:
			return False"""

	class Meta:
		ordering = ['active', 'name', '-sale_price']

class Cashdesk(models.Model):
	"""
	Cashdesks
	"""
	name = models.CharField(max_length=255, unique=True, verbose_name="Unique identifier of that cashdesk (internal)")
	invoice_name = models.CharField(max_length=255, unique=True, verbose_name="Unique identifier of that cashdesk (to show on invoice, keep it short)")

	ip = models.IPAddressField(unique=True, verbose_name="IP Address of this cashdesk (for access control and receipt printers)")

	receipt_printer = models.BooleanField(default=True, verbose_name="Does this cashdesk have a receipt printer?")
	receipt_printer_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Receipt printer name (optional)")
	invoice_printer = models.BooleanField(default=True, verbose_name="Does this cashdesk have an invoice printer?")
	invoice_printer_name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Invoice printer name (optional)")

	allow_supervisor = models.BooleanField(default=False, verbose_name="Allow supervisor login on this cashdesk?")
	active = models.BooleanField(default=False, verbose_name="Is this cashdesk enabled?")

	active_session = models.ForeignKey("CashdeskSession", related_name="active_session_set", unique=True, blank=True, null=True, verbose_name="Active CashdeskSession object (don't fill in)")

	def __unicode__(self):
		return "%s (%s)" % (self.name, self.ip)

	class Meta:
		ordering = ['name']

class CashdeskSession(models.Model):
	"""
	Sessions for Cashdesks -- without a session, a cashier can't do shit
	"""
	cashdesk = models.ForeignKey(Cashdesk, verbose_name="Cashdesk")
	cashier = models.ForeignKey(User, verbose_name="Cashier")
	supervisor_before = models.ForeignKey(User, related_name="supervised_before_cashdisksession_set", verbose_name="Supervisor (before session)")

	valid_from = models.DateTimeField(blank=False, null=False, verbose_name="Cashier can sell from..")
	valid_until = models.DateTimeField(blank=False, null=False, verbose_name="Cashier can sell until..")

	change = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Change the cashier has gotten before session start")

	is_logged_in = models.BooleanField(default=False, verbose_name="Is the cashier logged in at the cashdesk? (do not change manually)", editable=False)
	was_logged_in = models.BooleanField(default=False, verbose_name="Did the cashier ever log into this session? (do not change manually)", editable=False)
	cashier_has_ended = models.BooleanField(default=False, verbose_name="Did the cashier ended his session with logout? (do not change manually)", editable=True)

	drawer_sum = models.DecimalField(null=True, blank=True, max_digits=7, decimal_places=2, verbose_name="Amount of money in cash drawer after session")
	drawer_sum_ok = models.NullBooleanField(default=None, blank=True, null=True, verbose_name="Amount of money in cash drawer after session was okay")

	supervisor_after = models.ForeignKey(User, null=True, blank=True, related_name="supervised_after_cashdisksession_set", verbose_name="Supervisor (after session)")
	total = models.DecimalField(null=True, blank=True, max_digits=7, decimal_places=2, verbose_name="Actual winnings (after change)")

	notes = models.TextField(null=True, blank=True, verbose_name="Any additional notes for this cashdesk session")

	def get_reversed_positions(self):
		from c4sh.desk.models import SalePosition # this needs to be done here to avoid circular dependencies
		# fetch positions which sale is marked as not fulfilled and reversed
		positions_reversed = SalePosition.objects.filter(sale__session=self, sale__fulfilled=False, sale__reversed=True)
		positions_reversed_merged = {}
		total = 0
		for position in positions_reversed:
			if not positions_reversed_merged.get(position.ticket.pk):
				positions_reversed_merged[position.ticket.pk] = {
					'ticket': position.ticket,
					'amount': 1,
					'total': position.ticket.sale_price
				}
			else:
				positions_reversed_merged[position.ticket.pk]['amount'] += 1
				positions_reversed_merged[position.ticket.pk]['total'] = positions_reversed_merged[position.ticket.pk]['amount'] * positions_reversed_merged[position.ticket.pk]['ticket'].sale_price
			total = total + position.ticket.sale_price

		return {'positions': positions_reversed_merged, 'total': total}

	def get_merged_positions(self):
		from c4sh.desk.models import SalePosition # this needs to be done here to avoid circular dependencies
		# fetch positions which sale is marked as fulfilled and not reversed
		positions = SalePosition.objects.filter(sale__session=self, sale__fulfilled=True, sale__reversed=False)
		positions_merged = {}
		total = 0
		for position in positions:
			if not positions_merged.get(position.ticket.pk):
				positions_merged[position.ticket.pk] = {
					'ticket': position.ticket,
					'amount': 1,
					'total': position.ticket.sale_price
				}
			else:
				positions_merged[position.ticket.pk]['amount'] += 1
				positions_merged[position.ticket.pk]['total'] = positions_merged[position.ticket.pk]['amount'] * positions_merged[position.ticket.pk]['ticket'].sale_price

			total = total + position.ticket.sale_price

		return {'positions': positions_merged, 'total': total}

	def drawer_supposed_sum(self):
		return self.get_merged_positions()['total'] + self.change

	def get_passes(self):
		return CashdeskSessionPass.objects.filter(session=self)

	def __unicode__(self):
		return "#%d - %s at %s (%s - %s)" % (self.pk, self.cashier.username, self.cashdesk.name, self.valid_from.strftime("%d.%m. %H:%M"), self.valid_until.strftime("%d.%m. %H:%M"))

	class Meta:
		ordering = ['valid_from', 'cashdesk']


class HonoraryMember(models.Model):
	membership_number = models.CharField(unique=True, max_length=50, null=False, blank=False, verbose_name="Membership number of this member (e.g. Chausnummer). This is unique!")

c4sh/backend/forms.py
from django import forms
from c4sh.backend import models as bmodels
from c4sh.desk import models as dmodels
from c4sh.preorder import models as pmodels
from django.contrib.auth.models import User

class AddCashierForm(forms.Form):
	username = forms.RegexField(label="Username", max_length=30, regex=r'^[\w.@+-]+$',
		error_messages = {'invalid': "This value may contain only letters, numbers and @/./+/-/_ characters."})
	first_name = forms.CharField(label="First name")
	last_name = forms.CharField(label="Last name")
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput
		)

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1", "")
		password2 = self.cleaned_data["password2"]
		if password1 != password2:
			raise forms.ValidationError("The two password fields didn't match.")
		return password2

	def clean_username(self):
		username = self.cleaned_data["username"]
		try:
			User.objects.get(username=username)
		except User.DoesNotExist:
			return username
		raise forms.ValidationError("A user with that username already exists.")

class AddSessionForm(forms.ModelForm):
	class Meta:
		model = bmodels.CashdeskSession
		exclude = ('drawer_sum', 'drawer_sum_ok', 'supervisor_after', 'total', 'cashier_has_ended', )

class EditSessionForm(forms.ModelForm):
	class Meta:
		model = bmodels.CashdeskSession
		#exclude = ('cashier_has_ended',)

c4sh/templates/backend/cashdesks.html
{% extends "base/backend.html" %}
{% block content %}
		<article class="content-box col-2">
			<header>
				<h2>Cashdesks</h2>
			</header>
			<section>
				<h3 class="bb">Open</h3>
				<ul>
				{% for cd in cashdesks_open %}
					<li>{{cd.name}} ({{cd.active_session.cashier}}, {{cd.active_session.valid_from|date:"Y-m-d H:i:s"}} - {{cd.active_session.valid_until|date:"Y-m-d H:i:s"}})</li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>
				<h3 class="bb">Closed</h3>
				<ul>
				{% for cd in cashdesks_closed %}
					<li>{{cd.name}}</li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>
				<h3 class="bb">Disabled</h3>
				<ul>
				{% for cd in cashdesks_inactive %}
					<li>{{cd.name}}</li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>
			</section>
		</article>
		<article class="content-box col-2 clear-rm">
			<header>
				<h2>Cashiers</h2>
				<nav>
					<ul class="button-switch">
						<li><a href="{% url "backend-cashdesks-cashier-add" %}" class="button">Add</a></li>
					</ul>
				</nav>
			</header>
			<section>
				<h3 class="bb">Logged In</h3>
				<ul>
				{% for ch in cashiers_active %}
					<li>{{ch.cashier}} ({{ch.cashdesk}})</li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>
				<h3 class="bb">Others</h3>
				<ul>
				{% for cd in cashiers_inactive %}
					<li>{{cd.username}}</li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>

			</section>
		</article>

		<article class="content-box col-2">
			<header>
				<h2>Sessions</h2>
				<nav>
					<ul class="button-switch">
						<li><a href="{% url "backend-cashdesks-session-add" %}" class="button">Add</a></li>
					</ul>
				</nav>
			</header>
			<section>
				<h3 class="bb">Upcoming</h3>
				<ul>
				{% for us in sessions_upcoming %}
					<li><a href="{% url "backend-cashdesks-session-edit" us.pk %}">{{us}}</a></li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>

				<h3 class="bb">Active</h3>
				<ul>
				{% for as in sessions_active %}
					<li><a href="{% url "backend-cashdesks-session-edit" as.pk %}">{{as}}</a></li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>

				<h3 class="bb">Paused</h3>
				<ul>
				{% for ps in sessions_paused %}
					<li><a href="{% url "backend-cashdesks-session-edit" ps.pk %}">{{ps}}</a></li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>

				<h3 class="bb">Recently ended</h3>
				<ul>
				{% for rs in sessions_old %}
					<li><a href="{% url "backend-cashdesks-session-edit" rs.pk %}">{{rs}}</a></li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>

			</section>
		</article>

		<article class="content-box col-2 clear-rm minimizer">
			<header>
				<h2>Archive</h2>
			</header>
			<section>

				<ul>
				{% for os in sessions_archive %}
					<li><a href="{% url "backend-cashdesks-session-edit" os.pk %}">{{os}}</a></li>
				{% empty %}
					<li style="font-style: italic;">None</li>
				{% endfor %}
				</ul>

			</section>
		</article>
{% endblock %}

c4sh/templates/backend/cashdesks_cashier_add.html
{% extends "base/backend.html" %}
{% block content %}

		<article class="content-box col-2">
			<header>
				<h2>Add cashier</h2>
			</header>
			<section>
				<form method="POST" action="{% url "backend-cashdesks-cashier-add" %}">
				<table class="form">
				{% csrf_token %}
				{{form}}
				<tr>
					<td colspan="2" style="text-align:right;padding:10px 30px;">
						<input type="submit" class="button green" value="Add cashier"/>
					</td>
				</tr>
				</table>
			</form>
			</section>
		</article>
{% endblock %}

c4sh/templates/backend/cashdesks_session_add.html
{% extends "base/backend.html" %}
{% block content %}
<script type="text/javascript">
	$(document).ready(function() {
		$('#id_supervisor_before').val({{request.user.pk}});
	});
</script>
		<form method="POST" action="{% url "backend-cashdesks-session-add" %}">
			<article class="content-box col-2">
				<header>
					<h2>Basic settings</h2>
				</header>
				<section>
					<table class="form">
					{% csrf_token %}
					{{form}}
					</table>
				</section>
			</article>

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>Passes</h2>
				</header>
				<section>
					<table class="form">
						{% for pass in passes %}
						<tr>
							<td>{{pass.name}}</td>
							<td><input type="text" maxlength="6" name="passes_before[{{pass.pk}}]" /></td>
						</tr>
						{% endfor %}
					</table>
				</section>
			</article>

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>Create session</h2>
				</header>
				<section>
					<p style="float:left;">Make sure you entered the currect amount of money and passes before creating the session, please!</p>
					<input type="submit" class="button green" style="float:right;" value="Create session"/>
				</section>
			</article>
		</form>
{% endblock %}

c4sh/templates/backend/cashdesks_session_edit.html
{% extends "base/backend.html" %}
{% block content %}

<script type="text/javascript">
	$(document).ready(function() {
		//if ($('#id_supervisor_after').val() == "") {
			//$('#id_supervisor_after').val({{request.user.pk}});
		//}
	});
</script>
		<form method="POST" action="{% url "backend-cashdesks-session-edit" session.pk %}">
			<article class="content-box col-2">
				<header>
					<h2>Basic settings</h2>
				</header>
				<section>

					<table class="form">
					{% csrf_token %}
					{{form}}
					</table>
				</section>
			</article>

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>Tickets sold</h2>
				</header>
				<section>
					<table>
					<thead>
						<tr>
							<th>Amount</th>
							<th>Type</th>
							<th>Price</th>
							<th>Total</th>
						</tr>
					</thead>
					{% for p in positions_for_template %}
					<tr>
						<td>{{p.amount}}x</td>
						<td>{{p.ticket.name}}</td>
						<td>{{p.ticket.sale_price|floatformat:2}}
						{{p.ticket.currency}}</td>
						<td>{{p.total}} {{p.ticket.currency}}</td>
					</tr>
					{% endfor %}
					<thead>
					<tr>
						<th colspan="4" style="text-align:right;padding-right:20px;font-size:large;" id="cart-sum">{{total}} EUR</td>
					</tr>
					</thead>
					</table>
				</section>
			</article>

			{% if positions_reversed_for_template %}

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>Tickets reversed</h2>
				</header>
				<section>
					<table>
					<thead>
						<tr>
							<th>Amount</th>
							<th>Type</th>
							<th>Price</th>
							<th>Total</th>
						</tr>
					</thead>
					{% for p in positions_reversed_for_template %}
					<tr>
						<td>{{p.amount}}x</td>
						<td>{{p.ticket.name}}</td>
						<td>{{p.ticket.sale_price|floatformat:2}}
						{{p.ticket.currency}}</td>
						<td>{{p.total}} {{p.ticket.currency}}</td>
					</tr>
					{% endfor %}
					</table>
				</section>
			</article>

			{% endif %}

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>Passes</h2>
				</header>
				<section>
					<table>
						<thead>
							<tr>
								<th>Pass type</th>
								<th>Amount before</th>
								<th>Amount after</th>
							</tr>
						</thead>
						{% for pass in passes %}
						<tr>
							<td>{{pass.pass_type.name}}</td>
							<td><input style="width:50px;" type="text" maxlength="6" name="passes_before[{{pass.pk}}]" value="{{pass.before_session}}" /></td>
							<td><input style="width:50px;" type="text" maxlength="6" name="passes_after[{{pass.pk}}]" value="{% if pass.after_session %}{{pass.after_session}}{% endif %}"/></td>
							</tr>
						{% endfor %}
					</table>
				</section>
			</article>

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>€€€ &nbsp;</h2>
				</header>
				<section>
					<table style="font-size:large;">
						<tr>
							<td style="text-align:right;">Change before session:</td>
							<td style="text-align:right;padding-right:15px;">{{session.change}} EUR</td>
						</tr>
						<tr style="border-bottom:2px solid rgb(150,150,150);">
							<td style="text-align:right;">Received:</td>
							<td style="text-align:right;padding-right:15px;">{{total}} EUR</td>
						</tr>
						<tr>
							<td style="text-align:right;font-weight:bold;"></td>
							<td style="text-align:right;padding-right:15px;font-weight:bold;">{{session.drawer_supposed_sum}} EUR</td>
						</tr>
					</table>
				<div style="float:right;margin-top:10px;">
					<a target="_blank" href="{% url "backend-cashdesks-session-report" session.pk %}"><button onclick="window.location='{% url "backend-cashdesks-session-report" session.pk %}';return false;" class="button green">Print report</button></a>
				</div>
				</section>
			</article>

			<article class="content-box col-2 clear-rm">
				<header>
					<h2>Edit session</h2>
				</header>
				<section>
					<p style="float:left;">Please make sure everything is alright before editing the session.</p>
					<input type="submit" class="button green" style="float:right;" value="Save session"/>
				</section>
			</article>
		</form>
{% endblock %}

c4sh/templates/backend/sales.html
{% extends "base/backend.html" %}
{% block content %}
		<article class="content-box minimizer">
			<header>
				<h2>{{event}} Sales</h2>
			</header>
			<section>
				<div class="tab default-tab" id="tab2">
					<h3>Ticket sales</h3>
					<table class="datatable">
						<thead>
							<tr>
								<th>Sale no.</th>
								<th>Fulfilled</th>
								<th>Cashdesk</th>
								<th>Cashier</th>
								<th>Date</th>
								<th>Value</th>
								<th>Options</th>
							</tr>
						</thead>
						<tbody>
						{% for sale in sales %}
							<tr>
								<td>{{sale.pk}}</td>
								<td>{% if sale.fulfilled %}
									<img src="{{MEDIA_URL}}admin/img/admin/icon_success.gif" />
									{% else %}
									<img src="{{MEDIA_URL}}admin/img/admin/icon_error.gif" />
									{% endif %}</td>
								<td>{{sale.cashdesk}}</td>
								<td>{{sale.cashier}}</td>
								<td>{{sale.time|date:"Y-m-d H:i:s"}}</td>
								<td>{{sale.cached_sum|floatformat:2}}</td>
								<td>
										<ul class="actions">
											<li><a class="view tooltip" href="{% url "backend-sale-detail" sale.pk %}" title="View Sale">view</a></li>
										</ul>
								</td>
							</tr>
						{% endfor %}
						</tbody>
						<tfoot>
							<tr>
								<th>Sale no.</th>
								<th>Fulfilled</th>
								<th>Cashdesk</th>
								<th>Cashier</th>
								<th>Date</th>
								<th>Value</th>
								<th>Options</th>
							</tr>
						</tfoot>
					</table>
					</form>
				</div>
			</section>
		</article>
{% endblock %}